export const FETCH_LOGIN_PARAMS_REQUEST = "FETCH_LOGIN_PARAMS_REQUEST";
export const FETCH_LOGIN_PARAMS_SUCCESS = "FETCH_LOGIN_PARAMS_SUCCESS";
export const FETCH_LOGIN_PARAMS_FAILURE = "FETCH_LOGIN_PARAMS_FAILURE";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
